import { ComplianceRepository } from '../../ports/ComplianceRepository';
import { RouteRepository } from '../../ports/RouteRepository';
import { ComplianceBalance } from '../../domain/entities/ComplianceBalance';
import { BankingRepository } from '../../ports/BankingRepository';

export class CalculateCBUseCase {
  constructor(
    private readonly complianceRepository: ComplianceRepository,
    private readonly routeRepository: RouteRepository,
    private readonly bankingRepository: BankingRepository
  ) {}

  async execute(shipId: string, year: number): Promise<ComplianceBalance> {
    // Get route data for the ship (using routeId as shipId for simplicity)
    const route = await this.routeRepository.findByRouteId(shipId);
    
    if (!route || route.year !== year) {
      throw new Error(`Route not found for ship ${shipId} in year ${year}`);
    }

    // Calculate CB
    const cbGco2eq = ComplianceBalance.calculateForRoute(
      route.ghgIntensity,
      route.fuelConsumption,
      route.year
    );

    // Get existing compliance record or create new
    let compliance = await this.complianceRepository.findByShipAndYear(shipId, year);

    if (compliance) {
      // Update existing
      const updated = ComplianceBalance.create({
        id: compliance.id,
        shipId: compliance.shipId,
        year: compliance.year,
        cbGco2eq,
        adjustedCbGco2eq: compliance.adjustedCbGco2eq,
        createdAt: compliance.createdAt,
        updatedAt: new Date(),
      });
      return await this.complianceRepository.update(updated);
    } else {
      // Create new
      const newCompliance = ComplianceBalance.create({
        id: '', // Will be generated by repository
        shipId,
        year,
        cbGco2eq,
        adjustedCbGco2eq: null,
      });
      return await this.complianceRepository.save(newCompliance);
    }
  }

  async getAdjustedCB(shipId: string, year: number): Promise<ComplianceBalance> {
    let compliance = await this.complianceRepository.findByShipAndYear(shipId, year);

    if (!compliance) {
      // Calculate if doesn't exist
      compliance = await this.execute(shipId, year);
    }

    // Adjust CB based on banked amounts applied
    const appliedAmount = await this.bankingRepository.getTotalApplied(shipId, year);
    const adjustedCb = compliance.cbGco2eq + appliedAmount;

    // Update if changed
    if (compliance.adjustedCbGco2eq !== adjustedCb) {
      const updated = ComplianceBalance.create({
        id: compliance.id,
        shipId: compliance.shipId,
        year: compliance.year,
        cbGco2eq: compliance.cbGco2eq,
        adjustedCbGco2eq: adjustedCb,
        createdAt: compliance.createdAt,
        updatedAt: new Date(),
      });
      return await this.complianceRepository.update(updated);
    }

    return compliance;
  }
}

